---
title: "Objectives" 
lightbox: false
---

The contribution from the London AIC consists of technology deployment and supporting expertise, that enable a number of objectives (@fig-aic-objectives) over the two year programme. This contribution includes the following:

(1) **Federated Learning and Interoperability Platform (FLIP)**: FLIP consists of (a) secure data environments within NHS hospital Trusts for multi-modal imaging data, imaging metadata, and structured health record data in the OMOP common data model; and (b) a mechanism to query data and train AI models across these secure enclaves without the need to physically transfer data. FLIP is presently installed in four major London Trusts. Integrating FLIP into the SDE will enable hospital data (such as cancer data) to be surfaced into the LDS, and enable access to multi-modal data (such as DICOM imaging and digital pathology) for research in precision medicine.

(2) **CogStack**: As an advanced natural language processing platform, CogStack can turn the large quantities of health information that are found in narrative text, into structured and analysable data. Currently actively used in Trusts to assist with clinical coding from notes and clinic letters, CogStack can surface secondary care and cancer pathway data, and previously unseen primary care data, into the SDE ecosystem.         

(3) **AIC Data/AI Hub**: The AIC hosts health data and AI implementation expertise, that will provide practical support in analytics engineering, clinical informatics, data science, and machine learning (ML) development and deployment. Primary aims are to (a) help Integrated Care Boards (ICB) migrate data pipelines and analytics into common data models and terminologies within LDS environments; (b) extend these into reproducible pipelines for data science and predictive analytics deployment; and (c) work together and provide training to make ICBs self-sufficient in these capabilities. The AIC will also support the adoption and roll-out of the OMOP Common Data Model.

```{mermaid}
%%| fig-width: 6
%%| label: fig-aic-objectives
%%| fig-cap: "Summary of AIC work components and objectives. FLIP = Federated Learning and Interoperability Platform; ML = Machine Learning; EHR = Electronic Health Record"
flowchart LR
    FLIP["FLIP"] ==> A1["Standardising hospital 
                          imaging metadata"] 
    FLIP ==> A2[Technology installation]
    A1 ==> A3["Federated model training
              for research collaborations"]
    A2 ==> A3

    A2 ==> A4["Enabling hospital data
              querying and analytics"]
    B1 ==> A4

    COG["CogStack"] ==> B1["Standardising hospital 
                            EHR data"]
    COG ==> B2[LDS installation] ==> B3["Standardising primary care 
                                      unstructured data"]

    A4 ==> C3
    B3 ==> C3

    A3 ==> A5["Supporting SDE collaborations with
            deep phenotyping and multi-modal data"]
    A4 ==> A5

    HUB[Data/AI Hub] ==> C1["Assisting ICBs with migration 
                              of existing pipelines"]
    C1 ==> C2["Building standardised 
                cohort pipelines"]
    C2 ==> C3["Building reproducible analytics/ML 
              pipelines with sharable code base"]
    HUB ==> C4["Working with LDS and EHR suppliers 
              to enable 'last mile' return of insights"]

    C4 ==> C3

    HUB ==> C5["Standardising London SDE data
                into OMOP common data model"]              
    
    C5 ==> C2

    classDef yellow fill:#ed6, stroke:#333, stroke-width:1px
    classDef lightorange fill:#fb3, stroke:#333, stroke-width:1px
    classDef orange fill:#f81, stroke:#333, stroke-width:1px

    classDef yellowbase fill:#ed6, stroke:#333, stroke-width:4px
    classDef lightorangebase fill:#fb3, stroke:#333, stroke-width:4px
    classDef orangebase fill:#f81, stroke:#333, stroke-width:4px

    class FLIP yellowbase
    class A1,A2,A3,A4,A5 yellow
    class COG lightorangebase
    class B1,B2,B3 lightorange
    class HUB orangebase
    class C1,C2,C3,C4,C5 orange
```
