---
title: "Ways of Working" 
lightbox: false
---

## Roving teams

The London AI Centre operates through “roving teams”, which include engineers, analysts, and data/AI scientists, that work across different NHS data environments. As part of the SDE programme, roving teams will work to install technology and build data pipelines within NHS Trusts, in the London Data Service, and Integrated Care Board environments. Team members are employed by NHS Trusts affiliated with the AI Centre, and may hold honorary contracts to enable work at other locations. 

## Working with ICBs

As the LDS ICB environments share a common data model, any pipelines for cohort engineering or data science/analytics created in collaboration with one ICB, can be adapted and used for any other ICB (or deployed across multiple environments to create pan-London insights). This will also facilitate the use of shared terminologies, and validating / versioning / serving NHS-owned machine learning models across regions. As the SDE programme progresses, and depending on population health priorities, dedicated analysts can be brought into roving teams to help develop specific data science / AI applications or products.


