project:
  type: website
  output-dir: docs

website:
  title: "London SDE/AIC Programme"
  navbar:
    background: secondary
#  sidebar: 
#    style: "docked"
#    search: false
#    contents:
    left:
      - text: "OVERVIEW"
        menu: 
          - href: index.qmd
            text: Introduction
          - href: overview/0_sde.qmd
            text: What is the London SDE?
          - href: overview/1_objectives.qmd
            text: Objectives
          - href: overview/2_timeline.qmd
            text: Delivery Roadmap            
      - text: "TECHNOLOGY"
        menu: 
          - href: technology/3_flip.qmd
            text: FLIP
          - href: technology/4_cogstack.qmd
            text: CogStack                          
      - text: "POPULATION HEALTH"
        menu: 
          - href: 5_introduction.qmd
            text: Summary
          - href: 6_inequalities.qmd
            text: Health Inequalities
          - href: 7_cardiovascular.qmd
            text: Cardiovascular Disease
          - href: 8_cancer.qmd
            text: Cancer Pathways            
      - text: "REAL-WORLD DATA"
        menu: 
          - href: 5_introduction.qmd
            text: Summary
   
format:
  html:
    theme: zephyr
    mermaid:
      theme: neutral



