project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
    mermaid:
      theme: neutral
  docx: default
  pdf: default

execute:
  freeze: true



