---
title: "London SDE/AIC Programme: Introduction and Proposed Use-Cases"  
authors:
  - name: Dr. Joe Zhang _(Head of Data Science)_
    affiliation: London AI Centre / SDE
  - name: Prof. James Teo _(Clinical Director AI & Data)_
    affiliation: London AI Centre / SDE
  - name: Dr. Jorge Cardoso _(Chief Technology Officer)_
    affiliation: London AI Centre / SDE
  - name: Jawad Chaudhry _(Programme Lead)_
    affiliation: London AI Centre / SDE
  - name: Sigal Hachlili _(Director of AI, Data & Digital)_
    affiliation: London AI Centre / SDE

---

_Version 0.6 (last updated 2024 Apr 18)_

## Introduction

The [London AI Centre](https://www.aicentre.co.uk/) (AIC) has been commissioned as part of the London Secure Data Environment (SDE) programme for its latest phase: to extend AI technologies and analytics capabilities to stakeholders and data environments across London. This document summarises the latest state of planning for the programme, as an aid to internal and external stakeholders including Integrated Care Boards (ICB) and the wider London NHS ecosystem.

## What is the London SDE?

The London Secure Data Environment (SDE) is a pan-London NHS programme that is part of a national effort to enable secure and more powerful analytics for NHS, academic, and commercial users. Uniquely amongst regional peers, the London SDE does not focus on a single research platform. Rather, it places a focus on developing data infrastructure and capabilities that can support population health, care providers, and commissioners. This is in addition to building data environments that enable commercial research and development partnerships.

The SDE is led by **OneLondon**, as part of an overarching London Health Data Strategy, coalescing around three components (@fig-sde-summary):

(1) **London Data Service (LDS)**: hosted in North-East London, the LDS serves as a data engineering and service layer for pan-London primary care and secondary care data. It handles data extraction and linkage, and provisions data within secure analytics environments for both research and NHS users.

(2) **DiscoverNOW Research/Analytics Environment**: run by Imperial College Healthcare Partners in North-West London, DiscoverNOW supports governance and operation of secure research environments for academic, commercial, and NHS research and analytics.

(3) **London AI Centre (AIC)**: a national centre of excellence for applied data science and AI, the AIC provides frontier technology for data enrichment (CogStack), federated analytics (FLIP), and deployment of machine learning tools, as well as expertise in health data and advanced analytics.


```{mermaid}
%%| fig-width: 6
%%| label: fig-sde-summary
%%| fig-cap: "Summary of SDE components and data flows. Each London ICB is provisioned with its own data/analytics environment through the LDS. FLIP = Federated Learning and Interoperability Platform."
flowchart TD
    d1[GP Surgeries] ==>|Primary care data| LDS1[(London Data Service)]
    d2[NHS Digital] ==>|Commissioning datasets| LDS1
    d3[Local data sources] ==>|ICS data| ICB
    AIC1["CogStack in Trusts"] ==>|"Unstructured data 
                                          (hospitals)"| LDS1
    LDS1==> AIC1a["CogStack in LDS"]
    AIC1a==>|"Unstructured data 
                (primary care)"| LDS1
    LDS1 ==>|Linked data| NWL1[("DiscoverNOW Research & 
                                Analytics Environment")]

    AIC2["AIC FLIP"] ==> |"Multi-modal data 
                                          (imaging metadata)"| NWL1
    AIC2 ==> |Hospital cancer data| LDS1
    LDS1 ==>|Linked data| ICB[("Integrated Care Board 'Sandpits' 
                                x5: NEL/SEL/SWL/NWL/NCL")]

    ICB <==>|Collaborative analytics| AIC3[AIC Data/AI Hub]
    ICB <==>|Output Sharing| LDS2[Terminology/Code/Model Servers]
    AIC3 <==>|Output Sharing| LDS2
    NWL1 <==>|Output Sharing| LDS2

    classDef green fill:#ab9, stroke:#333, stroke-width:1px
    classDef blue fill:#89c, stroke:#333, stroke-width:1px
    classDef bluegreen fill:#9ca, stroke:#333, stroke-width:1px
    classDef lightblue fill:#ace, stroke:#333, stroke-width:1px
    classDef red fill:#c89, stroke:#333, stroke-width:1px
    classDef lightorange fill:#ca8, stroke:#333, stroke-width:1px
    classDef orange fill:#d96, stroke:#333, stroke-width:1px
    classDef purple fill:#a9c, stroke:#333, stroke-width:1px
    classDef bluegray fill:#9ab, stroke:#333, stroke-width:1px
    classDef gray fill:#fff, stroke:#333, stroke-width:1px

    class LDS1,LDS2 blue
    class ICB lightblue
    class AIC1,AIC1a,AIC2,AIC3 orange
    class NWL1,NWL2 bluegray
    class d1,d2,d3 bluegreen
```


## Technology and objectives

The contribution from the London AIC consists of technology deployment and supporting expertise, that enable a number of objectives (@fig-aic-objectives) over the two year programme. This contribution includes the following:

(1) **Federated Learning and Interoperability Platform (FLIP)**: FLIP consists of (a) secure data environments within NHS hospital Trusts for multi-modal imaging data, imaging metadata, and structured health record data in the OMOP common data model; and (b) a mechanism to query data and train AI models across these secure enclaves without the need to physically transfer data. FLIP is presently installed in four major London Trusts. Integrating FLIP into the SDE will enable hospital data (such as cancer data) to be surfaced into the LDS, and enable access to multi-modal data (such as DICOM imaging and digital pathology) for research in precision healthcare.

(2) **CogStack**: As an advanced natural language processing platform, CogStack can turn the large quantities of health information that are found in narrative text, into structured and analysable data. Currently actively used in Trusts to assist with clinical coding from notes and clinic letters, CogStack can surface secondary care and cancer pathway data, and previously unseen primary care data, into the SDE ecosystem.         

(3) **AIC Data/AI Hub**: The AIC hosts substantial health data and AI implementation expertise, that will provide practical support in data engineering, clinical informatics, data science, and machine learning (ML) development and deployment. Primary aims are to (a) help Integrated Care Boards (ICB) migrate data pipelines and analytics into common data models and terminologies within LDS environments; (b) extend these into reproducible pipelines for data science and predictive analytics deployment; and (c) work together to make ICBs self-sufficient in these capabilities. The AIC will also support the adoption and roll-out of the OMOP Common Data Model.   

```{mermaid}
%%| fig-width: 6
%%| label: fig-aic-objectives
%%| fig-cap: "Summary of AIC work components and objectives. FLIP = Federated Learning and Interoperability Platform; ML = Machine Learning."
flowchart LR
    FLIP["FLIP"] ==> A1["Standardising hospital 
                          imaging metadata"] 
    FLIP ==> A2[Technology installation]
    A1 ==> A3["Federated model training
              for research collaborations"]
    A2 ==> A3

    A2 ==> A4["Enabling hospital 
              data queries"]
    B1 ==> A4

    COG["CogStack"] ==> B1["Standardising hospital 
                            cancer data"]
    COG ==> B2[LDS installation] ==> B3["Standardising primary care 
                                      unstructured data"]

    A4 ==> C3
    B3 ==> C3

    HUB[Data/AI Hub] ==> C1["Assisting ICBs with migration 
                              of existing pipelines"]
    C1 ==> C2["Building standardised 
                cohort pipelines"]
    C2 ==> C3["Building reproducible analytics/ML 
              pipelines with sharable code base"]
    HUB ==> C4["Standardising London SDE data
                into OMOP common data model"]

    classDef yellow fill:#ed6, stroke:#333, stroke-width:1px
    classDef lightorange fill:#fb3, stroke:#333, stroke-width:1px
    classDef orange fill:#f81, stroke:#333, stroke-width:1px

    classDef yellowbase fill:#ed6, stroke:#333, stroke-width:4px
    classDef lightorangebase fill:#fb3, stroke:#333, stroke-width:4px
    classDef orangebase fill:#f81, stroke:#333, stroke-width:4px

    class FLIP yellowbase
    class A1,A2,A3,A4 yellow
    class COG lightorangebase
    class B1,B2,B3 lightorange
    class HUB orangebase
    class C1,C2,C3,C4 orange
```

As part of the SDE programme, resources from the AIC (including in clinical informatics, analytics engineering, and data science/machine learning) are available to support:

- Migration of existing ICB analytics into LDS 'Sandpits';
- Building pipelines into common data models, including OMOP;
- Constructing common definitions for patient cohorts/phenotypes;
- Building, deploying, and maintaining complex reproducible analytics/machine learning pipelines;
- Application of clinical domain expertise to deliver 'last mile' insights to clinicians;
- Monitoring and evaluating real-world impacts in data-driven pathways;
- Skill transfer to embed advanced analytics capabiltiies in ICB teams.

As the LDS ICB environments share a common data model, any pipelines created in collaboration with an ICB can be adapted and used for any other ICB (or deployed across multiple environments to create pan-London insights). This will also facilitate the use of shared terminologies, and validating / versioning / serving NHS-owned machine learning models across regions.

## Proposed use-cases

The following use-cases are _examples_ of analytics projects that can be supported within the SDE ecosystem, in collaboration between ICB/NHS analytics teams and the AIC/SDE team. Use-cases align to the London Health Data Strategy and long term condition priorities, as well as national programmes such as CORE20PLUS5, and are proposed here following early discussions with London ICBs. An overarching objective for any work is to build a code base for reproducible analytics that can be shared between ICBs, and which can be improved collaboratively.

### Systematic measurement of group and individual health inequality 

**AIM:** To systematically surface multiple dimensions of health inequality across sociodemographic/geospatial groups and individual patients, and to monitor this data continuously across key long-term conditions.

**SUMMARY:** Health inequality refers to measurable differences in health outcomes and determinants between individuals or groups (e.g. morbidity, co-morbidity, disease complications/death, healthcare access, disease screening, treatment delivery). Where individuals and groups experience health inequality, the principle of health _equity_ emphases the importance of reducing disparities by modifying outcome determinants that are unfairly distributed. 

Health inequality is traditionally measured and visualised as a comparison of prevalence/incidence across different population groups. While helpful for broad insights, this offers limited understanding of complex individual circumstances. This type of measurement can be extended to individual patients, by using clinical domain knowledge to define 'indicators' of unequal disease, diagnosis, and treatment pathways. For example, in an individual with Diabetes Mellitus, indicators of inequality can include:

- Diabetes surfacing at an early age;
- Diagnosis in proximity to cardiovascular risk factor co-morbidities;
- Diagnosis at a _late_ age but with more severe disease, as measured by HbA1c or presence of end-organ complications;
- Reduced health engagement/encounters/treatment compared to what is expected based on disease severity;
- Shorter time to complications and mortality following diagnosis.

The precise contribution of factors to outcomes can be measured and understood in a multivariate statistical model. Overall, the presence and magnitude of indicators can be used to visualise, monitor, and explain different types of inequality, including through comparison of groups and individuals to 'what is expected' in a background population. The outcome is an increase in actionability, with identification of modifiable determinants of inequality ( = inequity) for small groups and individuals.

**METHODS:** The below shows an example workflow for a long-term condition (not including cancer). 

```{mermaid}
%%| fig-width: 6
flowchart LR
    A["Define terminologies for condition
        and supporting concepts"] ==> B["Reproducible pipelines creating per 
                                      group summary prevalence/incidence
                                      for any given cohort definition"]
    
    C["Define inequality indicators for 
    given condition based on domain
    knowledge and existing evidence"] ==> D["Multivariate regression and survival
                                              models to understand significance of
                                            inequality indicators on outcomes"]

    A ==> D

    D==>E["Given definition of group or individual: 
            visualise indicators of inequality 
            vs relevant baseline population"]

    classDef gray fill:#fff, stroke:#333, stroke-width:1px

    class A,B,C,D,E gray
```

**OUTPUTS:** The primary output of this project would be a code-base that engineers cohorts from disease definitions, produces indicators for a given disease, and produces summary tables and statistics for groups and individual patients (where required). The code can be adapted by ICBs and used to support local dashboards. Code can be used for higher-level interval reporting and monitoring for the London region.  


### Cardiovascular disease prevention through decision intelligence

**AIM:** To enhance descriptive population health management with explainable predictive analytics and clinical guideline-based decision support systems, across cardiovascular related co-morbidities (Hypertension, diabetes, chronic kidney disease).  

**SUMMARY:** 

**METHODS:**

**OUTPUTS:**


### Joining up cancer pathways

**AIM:**

**SUMMARY:** 

**METHODS:**

**OUTPUTS:**


### Secondary: Returning 'last mile' insights to primary care systems

**AIM:**

**SUMMARY:** 

**METHODS:**

**OUTPUTS:**
