---
title: "Objectives" 
lightbox: false
---

The London AI Centre (AIC) is providing technology deployment and expertise, to enable the following (@fig-aic-objectives):

(1) **Federated Learning and Interoperability Platform (FLIP)**: FLIP consists of (a) secure data environments within NHS hospital Trusts for structured health record data in the OMOP Common Data Model, multi-modal imaging data, and imaging metadata; and (b) a mechanism to query and analyse data ('Interoperability') and train AI models ('Federated Learning') across these secure enclaves without the need to physically transfer data. FLIP is presently installed in four major London Trusts. Integrating FLIP into the SDE will enable hospital data (such as cancer data) to be surfaced into the regional data ecosystem, and enable access to multi-modal data (such as DICOM imaging and digital pathology) for research in precision medicine.

(2) **NHS Hospital OMOP/CogStack**: AIC teams are working within NHS hospital Trusts to access data locked in propietary electronic systems, and standardise these into the OMOP Common Data Model. Alongside structured data, CogStack (an advanced natural language processing AI platform) is being used to turn the large quantities of health information found in narrative text into structured and analysable data. Currently actively deployed in Trusts to assist with clinical coding from notes and clinic letters, CogStack can surface secondary care and pathway data, and previously unseen primary care data, into the SDE ecosystem. Databases are owned by each NHS Trust, and are linked with FLIP to enable cross-site federated analyses.        

(3) **Data Science Teams for ICBs**: The AIC is providing practical support in clinical informatics, data science, and machine learning (ML) development and deployment. Primary aims are to (a) help Integrated Care Boards (ICB) migrate data pipelines and analytics into common data models and terminologies within LDS environments; (b) extend these into reproducible pipelines for data science, predictive analytics deployment and MLOps; and (c) work together and provide training to make ICBs self-sufficient in these capabilities. The AIC will also support the adoption and roll-out of the OMOP Common Data Model to enable future linkage to hospital data environments.

```{mermaid}
%%| fig-width: 6
%%| label: fig-aic-objectives
%%| fig-cap: "Summary of AI Centre work components and objectives. FLIP = Federated Learning and Interoperability Platform; ML = Machine Learning; EHR = Electronic Health Record"
flowchart LR
    FLIP["FLIP"] ==> A1["Standardising hospital 
                          imaging metadata"] 
    FLIP ==> A2[Technology installation]
    A1 ==> A3["Federated model training
              for research collaborations"]
    A2 ==> A3

    A2 ==> A4["Enabling hospital data
              querying and analytics"]
    B1 ==> A4

    COG["OMOP/CogStack"] ==> B1["Standardising hospital 
                            EHR data"]
    COG ==> B2[LDS installation] ==> B3["Standardising primary care 
                                      unstructured data"]

    A4 ==> C3
    B3 ==> C3

    A3 ==> A5["Supporting SDE collaborations with
            deep phenotyping and multi-modal data"]
    A4 ==> A5

    HUB[Data Science Teams] ==> C1["Assisting ICBs with migration 
                              of existing pipelines"]
    C1 ==> C2["Building standardised 
                cohort pipelines"]
    C2 ==> C3["Building reproducible analytics/ML 
              pipelines with sharable code base"]
    HUB ==> C4["Working with LDS and EHR suppliers 
              to enable 'last mile' return of insights"]

    C4 ==> C3

    HUB ==> C5["Standardising London SDE data
                into OMOP common data model"]              
    
    C5 ==> C2

    classDef yellow fill:#ed6, stroke:#333, stroke-width:1px
    classDef lightorange fill:#fb3, stroke:#333, stroke-width:1px
    classDef orange fill:#f81, stroke:#333, stroke-width:1px

    classDef yellowbase fill:#ed6, stroke:#333, stroke-width:4px
    classDef lightorangebase fill:#fb3, stroke:#333, stroke-width:4px
    classDef orangebase fill:#f81, stroke:#333, stroke-width:4px

    class FLIP yellowbase
    class A1,A2,A3,A4,A5 yellow
    class COG lightorangebase
    class B1,B2,B3 lightorange
    class HUB orangebase
    class C1,C2,C3,C4,C5 orange
```

## Roving teams

The London AIC operates through "Roving Teams", which include include those collaborating with NHS hospitals and population health centres such as ICBs. Teams may include engineers, data scientists, and developers who are working to install technology, and build data pipelines and analytics products. Team members are employees of NHS Trusts and universities affiliated with the AI Centre, and may hold honorary contracts to enable work at other locations.
